Maxwell
iron-claw-972/Activities-2024 pull request #3
Opened 2024-09-07 19:04 UTC by maxwtan

## Overview

This PR will..

## Activity Finished

## Tests Ran

## Additional Notes

2024-09-07 21:58 UTC, Kyle-Eldridge requested changes
There are some syntax  errors, and one spot that will cause the code to crash. You also need to test it on a robot. Once you finish these things and this PR is approved, you can continue working on Activity 2 (we will explain it in class on Monday).

2024-09-07 21:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/constants/DriveConstants.java
> +  public static final int RIGHT_MOTOR_1_ID = 6;
Deleting these lines causes an error. Add them back or remove the reference causing the error.

2024-09-07 21:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +  DifferentialDrivetrainSim cakeOrFake;
Instance variables should be private. Also, name this something more descriptive.

2024-09-07 21:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
>    // TODO 2.2.4: Create DifferentialDrivePoseEstimator
See above comment.

2024-09-07 21:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }
Test this code on Monday (you will have to invert one of the motors).

2024-09-07 21:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    tankDrive(Robot.driver.getLeftTranslation() * .25, Robot.driver.getRightTranslation() * .25);
This works, but you should multiply by .25 in tankDrive() instead of here so it works in later activites.

2024-09-07 21:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }
It should only update when the robot is in simulation, not when it isn't.

2024-09-14 01:24 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +  DifferentialDrivetrainSim cakeOrFake;
You changed it to be more descriptive, but make all of them private.

2024-09-14 01:25 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }
Invert right motor 1.

2024-09-15 22:55 UTC, johaj10 commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        DriveConstants.MEASUREMENT_STD_DEVS
You can indent these just to make it a little more readable.

2024-09-15 22:56 UTC, johaj10 commented on src/main/java/frc/robot/subsystems/Motor.java
> +import javax.management.ConstructorParameters;
This might be an unused import.

2024-09-20 01:55 UTC, Kyle-Eldridge commented
I am closing all remaining Activity 1 PRs. However, when you make a new PR when you finish Activity 2, you will still need to make any changes left on this PR before we approve the next one.

2024-09-20 01:55 UTC, closed without merging