Eileen
iron-claw-972/Activities-2024 pull request #5
Opened 2024-09-09 23:22 UTC by eileha

## Overview

This PR will..

## Activity Finished

*****inverted the motors, but it didn't do anything

## Tests Ran

## Additional Notes

2024-09-09 23:22 UTC, eileha commented
inverted motors

2024-09-10 03:11 UTC, Kyle-Eldridge requested changes
The code is mostly good, but there are 2 very small changes you should make. After you finish these, you can start Activity 2 (we will present it on Friday).

2024-09-10 03:11 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        rightMotor1.setInverted(true);
I'm still not sure why this part works. Change leftMotor1 to be not inverted for now so it's the same as everyone else's.

2024-09-10 03:11 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
Remove any unused imports. They should be underlined in yellow in your IDE.

2024-09-14 01:02 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +        rightMotor1.setInverted(false);
The right motor should be inverted, and the left motor should not be.

2024-09-20 01:54 UTC, Kyle-Eldridge commented
I am closing all remaining Activity 1 PRs. However, when you make a new PR when you finish Activity 2, you will still need to make any changes left on this PR before we approve the next one.

2024-09-20 01:54 UTC, closed without merging