Taran
iron-claw-972/Activities-2024 pull request #8
Opened 2024-09-27 22:23 UTC by moogoesmeow0

## Overview

This PR will..
do a ting

## Activity Finished

2

## Tests Ran

none

## Additional Notes

zooom
![among-us-gif-twerk-3230420954](https://github.com/user-attachments/assets/b4723b9f-a29c-4156-95b2-68a4419a4d4a)

2024-09-28 01:39 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +  AHRS gyro = new AHRS(SPI.Port.kMXP);
Make all instance variables private.

2024-09-28 01:55 UTC, Kyle-Eldridge requested changes
Although most of the code is close, there are several bugs that would prevent it from working. There are also a few formatting errors.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
drivePose should be defined outside the if statement so it will exist for both real and simulated robots.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    tankDrive(Robot.driver.getRawLeftTranslation(), Robot.driver.getRawRightTranslation());
Use getLeft/RightPosition(), without the "Raw". This squares the joystick results, which makes it easier to control.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +      driveSim.update(Constants.LOOP_TIME);
You do not need an empty if statement. You can either use ! or RobotBase.isSimulation().

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +      rightMotor1.set(rightPower * 1);
At least on the real robot, change these back to 0.25. You can leave them at 1 in the sim.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }else{
For the real robot, you need to divide by the gear ratio and multiply by the wheel circumference. Do not change the sim version, only the one for the real robot.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Ting.java
> +    MechanismLigament2d ligma;
All instance variables should be private. To access ting1, use a get method. Also, you only have one motor, so you can remove motor2. They put a Falcon 500 on the robot, so you should change this to a TalonFX as well.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Ting.java
> +        ting1.getRoot("pivot", 50, 50).append(ligma);
getName() is a function that returns the name of the class. You should put a String literal here instead.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Ting.java
> +        }
You should call the set method whether or not it's real. The only difference should be the value you pass to it.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Ting.java
> +        }else{
Use setInputVoltage(). setInput is inherited from a much more general superclass. You also need to pass in the voltage, not 3. You also call motor.set() twice.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Ting.java
> +        }
After calling setMotor(), you need to update the ligament using the current position (not the current position plus a constant).

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Ting.java
> +            return Units.radiansToDegrees(arm.getAngleRads());
Your units don't match. getPosition() is in rotations and the value you return for sim is in degrees.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/util/ShuffleBoard/Tabs/SubsystemTab.java
> +        ting = new Ting(motorId);
Instead of creating a new Ting here, pass in a Ting as a parameter.

2024-09-28 01:55 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/util/ShuffleBoard/ShuffleBoardManager.java
> +        subsystemTab = new SubsystemTab(0);
You need to add a new parameter to the ShuffleboardManager constructor for your Ting and then pass it into subsystemTab.

2024-10-01 22:02 UTC, moogoesmeow0 commented
I fixed the things that were requested
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.tenor.com%2FxUG50Jtht7QAAAAC%2Fminions-yay.gif&f=1&nofb=1&ipt=e5fdeea66c7564aab86ca8c8e63466a124253175af96eff53e188e5427d4d96f&ipo=images)

2024-10-02 00:23 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
Now this causes errors. To fix them, either move it after the if statement or use 0 instead of getLeft/RightPosition().

2024-10-02 00:28 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    }else{
You  need to do the same thing for the right motor.

2024-10-02 00:33 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Ting.java
> +        }else{
Like in tankDrive() you need to use speed * Constants.ROBOT_VOLTAGE.

2024-10-02 00:38 UTC, Kyle-Eldridge commented
You did not fix all of the things that were requested yet. See the unresolved comments. It's easier to see them on the [GitHub website](https://github.com/iron-claw-972/Activities-2024/pull/8), and you might need to press "show more".

2024-10-02 22:27 UTC, Kyle-Eldridge approved these changes

2024-10-02 22:27 UTC, closed without merging